import pandas as pd 
df1 = pd.read_csv('C:\\Users\\Admin\\Desktop\\dvf_project\\Data_lake\\raw\\dvf_stats_mensuelles.csv') 
df2 = pd.read_csv('C:\\Users\\Admin\\Desktop\\dvf_project\\Data_lake\\raw\\dvf_stats_geographiques_globales.csv')
print(df1.head()) 
print(df2.head())
print(df1.shape) 
print(df2.shape)
print(df1.info()) 
print(df2.info())
print(df1.describe()) 
print(df2.describe())
print('Rows:', len(df1)) 
print(df1.isna().sum())
print('Rows:', len(df2)) 
print(df2.isna().sum()) 